[package]
name = "simple"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
luminair_cairo = {path="../../../zkVMs/cairo"}
luminal.workspace = true
luminal_nn.workspace = true