[workspace]
resolver = "2"
members = ["backends/stwo"]

[workspace.package]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/raphaelDkhn/Luminair"
license = "MIT"
license-file = "LICENSE"

[workspace.dependencies]
luminal = { git = "https://github.com/raphaelDkhn/luminal.git", rev = "0309ea4" }
luminal_cpu = { git = "https://github.com/raphaelDkhn/luminal.git", rev = "0309ea4" }
luminal_nn = { git = "https://github.com/raphaelDkhn/luminal.git", rev = "0309ea4" }
