[workspace]
resolver = "2"
members = ["examples/cairo/*", "backends/cairo"]

[workspace.package]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/raphaelDkhn/Luminair"
license = "MIT"
license-file = "LICENSE"

[workspace.dependencies]
luminal = { git = "https://github.com/jafioti/luminal.git", rev = "d311003" }
luminal_cpu = { git = "https://github.com/jafioti/luminal.git", rev = "d311003" }
luminal_nn = { git = "https://github.com/jafioti/luminal.git", rev = "d311003" }