[workspace]
resolver = "2"
members = ["crates/air", "crates/compiler"]

[workspace.package]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/raphaelDkhn/Luminair"
license = "MIT"
license-file = "LICENSE"

[workspace.dependencies]
stwo-prover = { git = "https://github.com/starkware-libs/stwo.git", rev = "36b17ac" }
rayon = "1.10.0"
