[workspace]
resolver = "2"
members = ["examples/cairo/*", "zkVMs/cairo"]

[workspace.package]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/raphaelDkhn/Luminair"
license = "MIT"
license-file = "LICENSE"
