name: Benchmark and Publish

on:
  push:
    branches:
      - stwo-backend
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release

      - name: Clean Previous Benchmark Data
        run: |
          if [ -d ./target/criterion ]; then
            rm -rf ./target/criterion
          fi

      - name: Cache Benchmark Data
        uses: actions/cache@v3
        id: cache-bench
        with:
          path: ./target/criterion
          key: ${{ runner.os }}-bench-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bench-

      - name: Run Benchmarks
        run: cargo bench --bench tensor_ops

      - name: Prepare Benchmark Results
        run: |
          # Create the benchmarks directory structure
          mkdir -p processed_benchmarks/benchmarks
          cp -r target/criterion/* processed_benchmarks/benchmarks/
          # Rename long directories to shorter versions if needed
          cd processed_benchmarks/benchmarks
          if [ -d "TensorAdd_verification" ]; then
            mv "TensorAdd_verification" "verify"
          fi
          if [ -d "TensorAdd_proving" ]; then
            mv "TensorAdd_proving" "prove"
          fi
          if [ -d "TensorAdd_tracing" ]; then
            mv "TensorAdd_tracing" "trace"
          fi

      - name: Process Benchmark Results
        uses: joshua-auchincloss/criterion-pages@v1
        with:
          path: "./processed_benchmarks"
          config: |
            {
              "title": "LuminAIR Benchmark, by Giza",
              "header": "Performance Metrics on supported operators",
              "description": "Performance benchmarks for tensor operators (stwo-backend support)",
              "css": {
                "footer": {
                  "display": "none"
                },
                "title": {
                  "text-align": "center",
                  "font-family": "Arial, sans-serif",
                  "font-size": "2.5em"
                },
                "header": {
                  "text-align": "center",
                  "color": "#333",
                  "margin-bottom": "1em"
                }
              },
              "template": {
                "index": "./processed_benchmarks/custom_index.html"
              }
            }
            
      - name: Create Custom Index Template
        run: |
          cat > processed_benchmarks/custom_index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <title>${title}</title>
              <style>
                  .footer { display: none !important; }
                  body { font-family: Arial, sans-serif; }
                  h1 { font-size: 2.5em; text-align: center; color: #333; }
                  .header { text-align: center; margin-bottom: 2em; }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>${header}</h1>
                  <p>${description}</p>
              </div>
              <div class="content">
                  ${content}
              </div>
          </body>
          </html>
          EOL            
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Benchmark Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./processed_benchmarks"

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: benchmark
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Benchmark Results
        id: deployment
        uses: actions/deploy-pages@v2
