name: Benchmark

on:
  push:
    branches:
      - stwo-backend

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-12-17

      - name: Run benchmark
        run: |
          # Run benchmarks and format output
          cargo bench --bench tensor_ops 2>&1 | awk '
            /time:/ {
              name=$1
              split($4, times, " ")
              gsub(/[\[\],]/, "", times[1])
              
              # Convert to nanoseconds
              time=times[1]
              if ($5 ~ /µs/) time=time*1000
              if ($5 ~ /ms/) time=time*1000000
              
              printf "test %s ... bench: %d ns/iter (+/- 0)\n", name, time
            }
          ' > output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "200%"
          comment-on-alert: true
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
