name: Benchmark

on:
  push:
    branches:
      - stwo-backend

permissions:
  deployments: write
  contents: write
  pages: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-12-17
          components: rustfmt, clippy

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y gnuplot jq

      - name: Run benchmark and process results
        run: |
          # Create a directory for the benchmark results
          mkdir -p target/criterion

          # Run the benchmark
          cargo bench --bench tensor_ops

          # Process Criterion's output into a format compatible with benchmark-action
          echo '{"command":"benchmark","mean":' > bench_result.json
          cat target/criterion/TensorAdd/new/estimates.json | jq '.mean.point_estimate' >> bench_result.json
          echo ',"unit":"ns"}' >> bench_result.json

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Criterion Benchmark
          tool: "customBiggerIsBetter"
          output-file-path: bench_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/stwo-backend'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cache
          publish_branch: gh-pages
          keep_files: true
