name: Benchmark and Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-01-02

      - name: Clean Previous Benchmark Data
        run: |
          if [ -d ./target/criterion ]; then
            rm -rf ./target/criterion
          fi

      - name: Cache Benchmark Data
        uses: actions/cache@v3
        id: cache-bench
        with:
          path: ./target/criterion
          key: ${{ runner.os }}-bench-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bench-

      - name: Run Benchmarks
        run: cargo bench --bench tensor_ops

      - name: Prepare Benchmark Results
        run: |
          # Create the benchmarks directory structure
          mkdir -p processed_benchmarks/benchmarks
          cp -r target/criterion/* processed_benchmarks/benchmarks/

          # Rename directories for TensorAdd benchmarks
          cd processed_benchmarks/benchmarks
          if [ -d "TensorAdd/tracing" ]; then
            mv "TensorAdd/tracing" "tensor_add_trace"
          fi
          if [ -d "TensorAdd/proving" ]; then
            mv "TensorAdd/proving" "tensor_add_prove"
          fi
          if [ -d "TensorAdd/verification" ]; then
            mv "TensorAdd/verification" "tensor_add_verify"
          fi

          # Rename directories for TensorMul benchmarks
          if [ -d "TensorMul/tracing" ]; then
            mv "TensorMul/tracing" "tensor_mul_trace"
          fi
          if [ -d "TensorMul/proving" ]; then
            mv "TensorMul/proving" "tensor_mul_prove"
          fi
          if [ -d "TensorMul/verification" ]; then
            mv "TensorMul/verification" "tensor_mul_verify"
          fi

      - name: Process Benchmark Results
        uses: joshua-auchincloss/criterion-pages@v1
        with:
          path: "./processed_benchmarks"
          config: |
            {
              "title": "LuminAIR Tensor Operations Benchmark Results",
              "template": {
                "index": "index.html"
              },
              "groups": {
                "tensor_add_trace": "TensorAdd Tracing Performance",
                "tensor_add_prove": "TensorAdd Proving Performance",
                "tensor_add_verify": "TensorAdd Verification Performance",
                "tensor_mul_trace": "TensorMul Tracing Performance",
                "tensor_mul_prove": "TensorMul Proving Performance",
                "tensor_mul_verify": "TensorMul Verification Performance"
              },
              "css": {
                "footer": {
                  "display": "none"
                },
                "body": {
                  "font-family": "Arial, sans-serif"
                },
                "h1": {
                  "text-align": "center",
                  "font-size": "2.5em",
                  "color": "#333"
                }
              }
            }

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Benchmark Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./processed_benchmarks"

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: benchmark
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Benchmark Results
        id: deployment
        uses: actions/deploy-pages@v2
