name: Rust CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Setup Rust using the specific nightly version
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-01-02
        components: rustfmt, clippy
    
    # Cache dependencies to speed up builds
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    
    # Clean cargo cache to ensure fresh build
    - name: Clean cargo cache
      run: cargo clean
    
    # Build with verbose output
    - name: Build
      run: cargo build --verbose
    
    # Run tests
    - name: Run tests
      run: cargo test --verbose